import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import LangWrapper from "@/components/lang/LangWrapper";
import ScormWrapper from "@/components/scorm/ScormWrapper";
import DebugToggle from "@/components/debug/DebugToggle";
import DebugPanel from "@/components/debug/DebugPanel";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "NextScorm",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${poppins.variable} font-sans antialiased`}>
                <LangWrapper>
                    <ScormWrapper>
                        <DebugToggle />
                        <DebugPanel />
                        {children}
                    </ScormWrapper>
                </LangWrapper>
            </body>
        </html>
    );
}
